version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  ecomovil-api:
    build: .
    container_name: ecomovil-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://ecomovil.cqzckuuccbtd.us-east-1.rds.amazonaws.com:3306/ecomovilaceituna?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=ecomovilaceituna
      - SPRING_DATASOURCE_PASSWORD=123Fer53
